### ISSUE TITLE
Release version 0.2.0

### ISSUE THREAD

**Issue by ScottWales** [coecms/ARCCSSive#10]
What is required for us to make the new database format official?

**Comment by paolap** [comment]
I was going to look into this today, i guess the main issue is that drstree will eventually changed, but since this now won't happen anymore "next week" but in maybe a couple of months time, we might as well release the new version. I'll change the database name to something sensible, double check everything is working fine.

**Comment by paolap** [comment]
Hi Scott,

I've changed the db name to cmip5_replica.db. This is the same directory as before, in fact I copied it so I can keep the other for testing. I've run again a few things it's seems ok to me, mostly regardless of bugs there's no point on using the current stable version at all.
I'll try to add the bulk replicated data to the db, but I'll do that on the copy first, since it's complicated to work out the duplicated records, then it will really reflect what's available on raijin

**Comment by paolap** [comment]
v0.2.0 is now released I'm closing this
